server:
  port: ${PORT:1221}
spring:
  application:
    name: apifactus
    version: 1.0.1
  datasource:
    url: ${DB_URL_RENDER}
    username: ${DB_USER_RENDER}
    password: ${DB_PASS_RENDER}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  security:
    user:
      name: ${FSX_USER_API}
      password: ${FSX_PASS_API}
      roles: USER
  cache:
    type: simple
api:
  url: ${URL_FACTUS}
  user: ${USER_FACTUS}
  pass: ${PASS_FACTUS}
  id: ${ID_FACTUS}
  secret: ${SECRET_FACTUS}
